In [119]:
# commData
# #print target
# xMat = mat(commData)
# print xMat
# print xMat.shape
# xMat = xMat.astype(float)

# yMat = mat(target).T
# print yMat
# print yMat.shape
# yMat = yMat.astype(float)
# yMat

#d2, l2 = regression.loadDataSet("communities.csv")

# xMat.T
# xTx = xMat.T * xMat
# xTx
# linalg.det(xTx)
# #reload(regression)
# #d,l = regression.loadDataSet2('ex0.txt')
# #ws = regression.standRegres(d,l)
# #d[0:2]
# #ws

In [120]:
import numpy as np
from numpy import genfromtxt
from numpy import array
from numpy import mat
from numpy import linalg
from numpy import set_printoptions
import regression

In [121]:
commDataWithLabels = np.genfromtxt("communities.csv",delimiter=",",usecols=(range(2,100)),dtype=None)
print commDataWithLabels

[['population' 'householdsize' 'racepctblack' ..., 'PopDens'
  'PctUsePubTrans' 'ViolentCrimesPerPop']
 ['0.19' '0.33' '0.02' ..., '0.26' '0.2' '0.2']
 ['0' '0.16' '0.12' ..., '0.12' '0.45' '0.67']
 ..., 
 ['0.16' '0.37' '0.25' ..., '0.32' '0.18' '0.23']
 ['0.08' '0.51' '0.06' ..., '0.38' '0.33' '0.19']
 ['0.2' '0.78' '0.14' ..., '0.3' '0.05' '0.48']]


In [122]:
labels=array(commDataWithLabels[0,:])
print len(labels)
print labels

98
['population' 'householdsize' 'racepctblack' 'racePctWhite' 'racePctAsian'
 'racePctHisp' 'agePct12t21' 'agePct12t29' 'agePct16t24' 'agePct65up'
 'numbUrban' 'pctUrban' 'medIncome' 'pctWWage' 'pctWFarmSelf' 'pctWInvInc'
 'pctWSocSec' 'pctWPubAsst' 'pctWRetire' 'medFamInc' 'perCapInc'
 'whitePerCap' 'blackPerCap' 'indianPerCap' 'AsianPerCap' 'OtherPerCap'
 'HispPerCap' 'NumUnderPov' 'PctPopUnderPov' 'PctLess9thGrade'
 'PctNotHSGrad' 'PctBSorMore' 'PctUnemployed' 'PctEmploy' 'PctEmplManu'
 'PctEmplProfServ' 'MalePctDivorce' 'MalePctNevMarr' 'FemalePctDiv'
 'TotalPctDiv' 'PersPerFam' 'PctFam2Par' 'PctKids2Par' 'PctYoungKids2Par'
 'PctTeen2Par' 'PctWorkMomYoungKids' 'PctWorkMom' 'NumIlleg' 'PctIlleg'
 'NumImmig' 'PctImmigRecent' 'PctImmigRec5' 'PctImmigRec8' 'PctImmigRec10'
 'PctRecentImmig' 'PctRecImmig5' 'PctRecImmig8' 'PctRecImmig10'
 'PctSpeakEnglOnly' 'PctNotSpeakEnglWell' 'PctLargHouseFam'
 'PctLargHouseOccup' 'PersPerOccupHous' 'PersPerOwnOccHous'
 'PersPerRentOccHous' 'PctPersOw

In [123]:
print type(commDataWithLabels)
print commDataWithLabels.shape

<type 'numpy.ndarray'>
(1995L, 98L)


In [124]:
commData = array(commDataWithLabels[1:], dtype=float)
target = array(commData[:,-1], dtype=float)

In [125]:
commData

array([[ 0.19,  0.33,  0.02, ...,  0.26,  0.2 ,  0.2 ],
       [ 0.  ,  0.16,  0.12, ...,  0.12,  0.45,  0.67],
       [ 0.  ,  0.42,  0.49, ...,  0.21,  0.02,  0.43],
       ..., 
       [ 0.16,  0.37,  0.25, ...,  0.32,  0.18,  0.23],
       [ 0.08,  0.51,  0.06, ...,  0.38,  0.33,  0.19],
       [ 0.2 ,  0.78,  0.14, ...,  0.3 ,  0.05,  0.48]])

In [126]:
target

array([ 0.2 ,  0.67,  0.43, ...,  0.23,  0.19,  0.48])

In [127]:
rows = []
rows[:0] = labels[0:3]
#print rows
for i in range(0,97):
    item = array(commData[:,i], dtype=float)
    #print labels[i] item  #array of values for ith variable
    item_mean = item.mean()
    item_std = item.std()
    item_min = item.min()
    item_max = item.max()
#     print labels[i]
#     print "Mean: ", item_mean
#     print "Std:  ", item_std
#     print "Min:  ", item_min
#     print "Max:  ", item_max
#     print

In [128]:
reload(regression)

<module 'regression' from 'regression.pyc'>

In [129]:
ws = regression.standRegres(commData, target)

In [130]:
ws

matrix([[  5.92939621e-13],
        [  2.10101961e-13],
        [  3.57136404e-14],
        [  9.39124095e-14],
        [  1.66444728e-14],
        [  9.65425744e-14],
        [ -5.03830900e-13],
        [ -4.29267961e-13],
        [  6.23531804e-13],
        [  4.77319666e-14],
        [ -7.26737577e-13],
        [  1.70968708e-14],
        [ -3.51081399e-14],
        [  8.19069775e-14],
        [  1.38743645e-14],
        [ -1.34705701e-14],
        [ -6.77604758e-14],
        [  2.85237588e-14],
        [  8.28384189e-14],
        [  9.02591307e-15],
        [ -2.51779474e-13],
        [  3.17576448e-13],
        [  3.40781102e-15],
        [  1.40187279e-15],
        [ -2.68264854e-15],
        [  1.87421322e-17],
        [ -1.58994130e-14],
        [  4.10972098e-15],
        [  8.45171547e-14],
        [ -9.14244700e-14],
        [  1.01081285e-13],
        [ -3.15096754e-14],
        [  1.03610677e-14],
        [  6.96048148e-14],
        [  2.16070201e-14],
        [ -3.3460333

In [131]:
xMat=mat(commData)
yMat=mat(target)
yHat=xMat*ws

import matplotlib.pyplot as plt
fig = plt.figure()
ax=fig.add_subplot(111)
ax.scatter(xMat[:,1].flatten().A[0], yMat.T[:,0].flatten().A[0])

xCopy = commData.copy()
xCopy.sort(0)
yHat=xCopy*ws
ax.plot(xCopy[:,1], yHat)
plt.show()

In [132]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
from sklearn import svm

In [133]:
linreg=LinearRegression()
linreg.fit(commData, target)

LinearRegression(copy_X=True, fit_intercept=True, normalize=False)

In [134]:
print linreg.predict(commData[:10])

[ 0.2   0.67  0.43  0.12  0.03  0.14  0.03  0.55  0.53  0.15]


In [135]:
#RMSE

p=linreg.predict(commData)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))
print rmse_train

1.3397170363e-15


In [136]:
linreg.coef_

array([ -9.90571150e-16,  -5.93731980e-16,  -5.80829127e-16,
         8.58734549e-16,  -4.87181164e-16,  -7.70580600e-16,
        -1.18036328e-15,  -8.03258285e-17,   9.10050504e-16,
        -9.03074341e-16,  -3.02184086e-15,  -6.07801409e-16,
         4.86148631e-16,  -7.41221591e-16,  -4.02659505e-16,
        -8.74168918e-16,  -7.48437465e-16,  -1.55227893e-16,
        -4.64486610e-16,   6.02445619e-16,  -1.12757365e-15,
         6.17144817e-16,   2.66027850e-16,  -4.64844588e-16,
        -2.11367093e-16,   3.16953614e-16,  -8.18763223e-18,
         3.03592702e-16,  -5.35041067e-16,  -5.67961002e-17,
        -3.98649611e-16,   1.28398336e-16,   9.26554518e-17,
         2.60881066e-16,  -6.09068040e-17,  -3.51021888e-16,
        -8.80914265e-17,   2.08614051e-16,  -4.88975180e-16,
         4.50919684e-16,  -7.27875740e-16,   2.39391840e-16,
        -7.04350247e-16,   1.69067776e-17,  -8.27974706e-20,
        -5.58559148e-16,  -2.46291770e-17,   1.11127546e-15,
         6.95745240e-16,

In [137]:
import pylab as pl

pl.plot(p,target,'ro')
pl.plot([-1,1],[-1,1], 'g-')
pl.xlabel('Predicted')
pl.ylabel('Real')
pl.show()


In [138]:
#KFold

from sklearn.cross_validation import KFold

kf=KFold(len(commData), n_folds=10)
xval_err=0
for train, test in kf:
    linreg.fit(commData[train],target[train])
    p=linreg.predict(commData[test])
    e=p-target[test]
    xval_err+=np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

In [139]:
print "Linear Regression"
print('RMSE on training: ', rmse_train)
print('RMSE on 10-fold CV: ', rmse_10cv)

Linear Regression
('RMSE on training: ', 1.3397170363013816e-15)
('RMSE on 10-fold CV: ', 1.2983805962017009e-15)


In [140]:
ridge = Ridge(fit_intercept=True, alpha=0.1)
ridge.fit(commData,target)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, solver='auto', tol=0.001)

In [141]:
p=ridge.predict(commData)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

kf=KFold(len(commData), n_folds=10)
xval_err=0
for train, test in kf:
    ridge.fit(commData[train],target[train])
    p=ridge.predict(commData[test])
    e=p-target[test]
    xval_err+=np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Ridge Regression"
print('RMSE on training: ', rmse_train)
print('RMSE on 10-fold CV: ', rmse_10cv)


Ridge Regression
('RMSE on training: ', 0.00038536644459225531)
('RMSE on 10-fold CV: ', 0.00045471712849677327)


In [142]:
a=0.2
x=commData
y=target

for name,met in[
        ('linear regression', LinearRegression()),
        ('elastic-net', ElasticNet(fit_intercept=True, alpha=a)),
        ('lasso', Lasso(fit_intercept=True, alpha=a)),
        ('ridge', Ridge(fit_intercept=True, alpha=a)),
        ]:
    met.fit(commData,target)
    p=met.predict(commData)
    e=p-target
    total_error=np.dot(e,e)
    rmse_train=np.sqrt(total_error/len(p))
    
    kf=KFold(len(commData), n_folds=10)
    err=0
    for train, test in kf:
        met.fit(commData[train],target[train])
        p=met.predict(commData[test])
        e=p-target[test]
        err+=np.dot(e,e)
    rmse_10cv = np.sqrt(err/len(commData))
    print('Method: ', name)
    print('RMSE on training: ', rmse_train)
    print('RMSE on 10-fold CV: ', rmse_10cv)
    print

('Method: ', 'linear regression')
('RMSE on training: ', 1.3397170363013816e-15)
('RMSE on 10-fold CV: ', 1.2983805962017009e-15)

('Method: ', 'elastic-net')
('RMSE on training: ', 0.23292647291156512)
('RMSE on 10-fold CV: ', 0.2329890689565956)

('Method: ', 'lasso')
('RMSE on training: ', 0.23292647291156512)
('RMSE on 10-fold CV: ', 0.2329890689565956)

('Method: ', 'ridge')
('RMSE on training: ', 0.00076532636729202761)
('RMSE on 10-fold CV: ', 0.00090022468848991041)



In [143]:
# Stochastic Gradient Descent with Penalty = l2, alpha=0.15

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='l2', alpha=0.15, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression"
print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv

Stochastic Gradient Descent Regression
RMSE on training:  0.0411046695527
RMSE on 10-fold CV:  0.0422154595382


In [144]:
# Stochastic Gradient Descent with Penalty = l1, alpha=0.15

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='l1', alpha=0.15, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression with Penalty = l1"
print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv

Stochastic Gradient Descent Regression with Penalty = l1
RMSE on training:  0.152843022986
RMSE on 10-fold CV:  0.152814033016


In [145]:
# Stochastic Gradient Descent with Penalty = elasticnet, alpha=0.15

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='elasticnet', alpha=0.15, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression with Penalty = elastic-net"
print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv

Stochastic Gradient Descent Regression with Penalty = elastic-net
RMSE on training:  0.0485582098109
RMSE on 10-fold CV:  0.0484295214419


In [146]:
# Stochastic Gradient Descent with Penalty = l2, alpha=0.25

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='l2', alpha=0.25, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression"
Stochastic Gradient Descent Regression with Penalty = l1print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv

SyntaxError: invalid syntax (<ipython-input-146-3858ba1b939b>, line 36)

In [ ]:
# Stochastic Gradient Descent with Penalty = l1, alpha=0.25

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='l1', alpha=0.25, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression with Penalty = l1"
print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv

In [ ]:
# Stochastic Gradient Descent with Penalty = elasticnet, alpha=0.25

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(commData)
x_s=scaler.transform(commData)

sgdreg=SGDRegressor(penalty='elasticnet', alpha=0.25, n_iter=200)


#RMSE

sgdreg.fit(x_s,target)
p=sgdreg.predict(x_s)
err=p-target
total_error=np.dot(err,err)
rmse_train=np.sqrt(total_error/len(p))

#RMSE using 10-fold x-validation

kf=KFold(len(commData), n_folds=10)
xval_err = 0
for train, test in kf:
    scaler=StandardScaler()
    scaler.fit(commData[train])
    xtrain_s = scaler.transform(commData[train])
    xtest_s = scaler.transform(commData[test])
    sgdreg.fit(xtrain_s, y[train])
    p=sgdreg.predict(xtest_s)
    e=p-target[test]
    xval_err += np.dot(e,e)
rmse_10cv=np.sqrt(xval_err/len(commData))

print "Stochastic Gradient Descent Regression with Penalty = elastic-net"
print 'RMSE on training: ', rmse_train
print 'RMSE on 10-fold CV: ', rmse_10cv