In [17]:
orig = array([[0, 2, 4, 0, 1, 0],
        [1, 3, 0, 0, 0, 2],
        [0, 1, 0, 2, 0, 0],
        [3, 0, 1, 5, 4, 0],
        [0, 4, 0, 0, 0, 1],
        [2, 7, 2, 1, 3, 0],
        [1, 0, 0, 5, 5, 1],
        [0, 1, 1, 0, 0, 3]])
print orig

[[0 2 4 0 1 0]
 [1 3 0 0 0 2]
 [0 1 0 2 0 0]
 [3 0 1 5 4 0]
 [0 4 0 0 0 1]
 [2 7 2 1 3 0]
 [1 0 0 5 5 1]
 [0 1 1 0 0 3]]


In [18]:
a = orig
print a

[[0 2 4 0 1 0]
 [1 3 0 0 0 2]
 [0 1 0 2 0 0]
 [3 0 1 5 4 0]
 [0 4 0 0 0 1]
 [2 7 2 1 3 0]
 [1 0 0 5 5 1]
 [0 1 1 0 0 3]]


In [35]:
row = a[0,:]
print row

[0 2 4 0 1 0]


In [50]:
rowList = row.tolist()
indicies = [i for i, x in enumerate(rowList) if x!= 0]
print len(indicies)

3


In [13]:
def numDocsContainingTerm(row):
    rowList = row.tolist()
    indicies = [i for i, x in enumerate(rowList) if x!= 0]
    return len(indicies)

In [78]:
import math

x = math.log( 6/4.0, 2)
print x

0.584962500721


In [4]:
import numpy as np

TD = np.genfromtxt('term-doc-mat.csv',delimiter=',',usecols=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),dtype=int)

In [10]:
print TD
DT = TD.T
#print DT

[[24 32 12  6 43  2  0  3  1  6  4  0  0  0  0]
 [ 9  5  5  2 20  0  1  0  0  0 27 14  3  2 11]
 [ 0  3  0  0  3  7 12  4 27  4  0  1  0  0  0]
 [ 3  0  0  0  0 16  0  2 25 23  7 12 21  3  2]
 [ 1  0  0  0  0 33  2  0  7 12 14  5 12  4  0]
 [12  2  0  0 27  0  0  0  0 22  9  4  0  5  3]
 [ 0  0  0  0  0 18 32 22 34 17  0  0  0  0  0]
 [ 1  0  0  0  2  0  0  0  3  9 27  7  5  4  4]
 [21 10 16  7 31  0  0  0  0  0  0  0  0  1  0]
 [ 2  0  0  2  0 27  4  2 11  8 33 16 14  7  3]]


In [ ]:
numTerms=len(DT[0])
NDocs = len(DT[:,0])
print numTerms
print NDocs

In [11]:
orig = TD
print orig

[[24 32 12  6 43  2  0  3  1  6  4  0  0  0  0]
 [ 9  5  5  2 20  0  1  0  0  0 27 14  3  2 11]
 [ 0  3  0  0  3  7 12  4 27  4  0  1  0  0  0]
 [ 3  0  0  0  0 16  0  2 25 23  7 12 21  3  2]
 [ 1  0  0  0  0 33  2  0  7 12 14  5 12  4  0]
 [12  2  0  0 27  0  0  0  0 22  9  4  0  5  3]
 [ 0  0  0  0  0 18 32 22 34 17  0  0  0  0  0]
 [ 1  0  0  0  2  0  0  0  3  9 27  7  5  4  4]
 [21 10 16  7 31  0  0  0  0  0  0  0  0  1  0]
 [ 2  0  0  2  0 27  4  2 11  8 33 16 14  7  3]]


In [23]:

import numpy as np
from numpy import array
from numpy import *
import math

freqs = orig.shape[0]
docs = orig.shape[1]
weightMatrix = zeros((freqs, docs))
tc = 0
for f in range(0,freqs):
    nk=numDocsContainingTerm(orig[f,:])
    for d in range(0,docs):
        tfik=orig[f,d]
        x = docs/float(nk)
        idfk = math.log((x), 2)
        w = tfik*idfk 
        weightMatrix[f,d] = w
np.set_printoptions(precision=2, suppress=True,linewidth=120)
print weightMatrix

[[ 14.04  18.72   7.02   3.51  25.15   1.17   0.     1.75   0.58   3.51   2.34   0.     0.     0.     0.  ]
 [  4.03   2.24   2.24   0.89   8.95   0.     0.45   0.     0.     0.    12.08   6.26   1.34   0.89   4.92]
 [  0.     2.72   0.     0.     2.72   6.35  10.88   3.63  24.49   3.63   0.     0.91   0.     0.     0.  ]
 [  1.75   0.     0.     0.     0.     9.36   0.     1.17  14.62  13.45   4.09   7.02  12.28   1.75   1.17]
 [  0.74   0.     0.     0.     0.    24.32   1.47   0.     5.16   8.84  10.32   3.68   8.84   2.95   0.  ]
 [ 10.88   1.81   0.     0.    24.49   0.     0.     0.     0.    19.95   8.16   3.63   0.     4.53   2.72]
 [  0.     0.     0.     0.     0.    28.53  50.72  34.87  53.89  26.94   0.     0.     0.     0.     0.  ]
 [  0.74   0.     0.     0.     1.47   0.     0.     0.     2.21   6.63  19.9    5.16   3.68   2.95   2.95]
 [ 27.76  13.22  21.15   9.25  40.98   0.     0.     0.     0.     0.     0.     0.     0.     1.32   0.  ]
 [  0.64   0.     0.     0.6

In [30]:
import kNN