In [1]:
from numpy import genfromtxt

import numpy as np
import pylab as pl

from sklearn.feature_extraction import DictVectorizer
from sklearn import preprocessing
from sklearn import neighbors, tree, naive_bayes
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
bankData = np.genfromtxt("bank_data.csv", delimiter=",", names=True, dtype=("|S10", int, float, int, "|S6", "|S10", "|S3", "|S3", "|S3", "|S3", "|S3", "|S3"))

In [3]:
print bankData.shape

(600L,)


In [4]:
bd_records = bankData[['age', 'income', 'children', 'gender', 'region', 'married', 'car', 'savings_acct', 'current_acct','mortgage']]
#bd_records

In [5]:
bd_names=bd_records.dtype.names
#bd_names

In [6]:
bd_target=bankData['pep']
#bd_target

In [7]:
bd_dict = [dict(zip(bd_names, record)) for record in bd_records]
#bd_dict[:5]

In [8]:
bd_vec = DictVectorizer()
bd_matrix = bd_vec.fit_transform(bd_dict).toarray()
bd_vec.get_feature_names()
print bd_matrix[0]
print len(bd_matrix) 

[  4.80000000e+01   1.00000000e+00   0.00000000e+00   1.00000000e+00
   1.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
   1.75460000e+04   1.00000000e+00   0.00000000e+00   1.00000000e+00
   0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   1.00000000e+00   0.00000000e+00]
600


In [9]:
tpercent = 0.8
tsize = tpercent * len(bd_matrix)
bd_train = bd_matrix[:tsize,:]
bd_test = bd_matrix[tsize:,:]
print bd_train.shape
print bd_test.shape
print bd_test

(480L, 19L)
(120L, 19L)
[[ 30.   1.   0. ...,   0.   1.   0.]
 [ 47.   0.   1. ...,   0.   0.   1.]
 [ 44.   1.   0. ...,   0.   0.   1.]
 ..., 
 [ 31.   0.   1. ...,   1.   0.   1.]
 [ 29.   1.   0. ...,   0.   0.   1.]
 [ 38.   0.   1. ...,   1.   1.   0.]]


In [10]:
min_max_scalar = preprocessing.MinMaxScaler()
bd_train_norm = min_max_scalar.fit_transform(bd_train)
bd_test_norm = min_max_scalar.fit_transform(bd_test)

print bd_train_norm[0]
print bd_test_norm[0]

[ 0.6122449   1.          0.          0.33333333  1.          0.          1.
  0.          0.21563448  1.          0.          1.          0.          1.
  0.          0.          0.          1.          0.        ]
[ 0.24489796  1.          0.          0.66666667  0.          1.          0.
  1.          0.09796027  0.          1.          0.          1.          0.
  1.          0.          0.          1.          0.        ]


In [11]:
bd_target_train = bd_target[:tsize]
bd_target_test = bd_target[tsize:]
print bd_target_test
print bd_target_test.shape

['NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES'
 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO'
 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO'
 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES'
 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'YES' 'YES'
 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO'
 'YES' 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO'
 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES']
(120L,)


In [12]:
#KNN Classifier

n_neighbors = 5
knnclf = neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
knnclf.fit(bd_train_norm, bd_target_train)
knnpreds_test = knnclf.predict(bd_test_norm)
print knnpreds_test

['YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES'
 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES'
 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO'
 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES'
 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'YES'
 'YES' 'YES' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES'
 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO'
 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES'
 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES']


In [13]:
# KNN - Classification Report

print(classification_report(bd_target_test, knnpreds_test))

             precision    recall  f1-score   support

         NO       0.62      0.68      0.65        62
        YES       0.62      0.55      0.58        58

avg / total       0.62      0.62      0.62       120



In [14]:
#KNN - Confusion Matrix

knncm = (confusion_matrix(bd_target_test, knnpreds_test))
print knncm

[[42 20]
 [26 32]]


In [15]:
#KNN - Confusion Matrix Plot

pl.matshow(knncm)
pl.title('KNN Classifier Confusion Matrix')
pl.colorbar()
pl.ylabel('Actual')
pl.xlabel('Predicted')
pl.show()

In [16]:
#Tree Classifier

treeclf = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=3)
treeclf = treeclf.fit(bd_train, bd_target_train)
treepreds_test = treeclf.predict(bd_test)
print treepreds_test

['NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'YES' 'YES'
 'YES' 'YES' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO'
 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES'
 'NO' 'YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'YES' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'NO'
 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO'
 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'YES'
 'YES']


In [17]:
#Tree Classifier - Classification Report

print(classification_report(bd_target_test, treepreds_test))

             precision    recall  f1-score   support

         NO       0.83      0.84      0.83        62
        YES       0.82      0.81      0.82        58

avg / total       0.82      0.82      0.82       120



In [18]:
#Tree Classifier - Confusion Matrix - Why is this zero???

treecm = confusion_matrix(bd_target_test, treepreds_test, labels=['Yes', 'No'])
print treecm

[[0 0]
 [0 0]]


In [19]:
#Tree Classifier - Confusion Matrix Plot

pl.matshow(treecm)
pl.title('Tree Classifier Confusion Matrix')
pl.colorbar()
pl.ylabel('Actual')
pl.xlabel('Predicted')
pl.show()

In [20]:
#Naive Bayes Classifier

nbclf = naive_bayes.GaussianNB()
nbclf = nbclf.fit(bd_train, bd_target_train)
nbpreds_test = nbclf.predict(bd_test)
print nbpreds_test

['NO' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO'
 'YES' 'NO' 'NO' 'YES' 'YES' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO'
 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO'
 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES' 'NO'
 'NO' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO'
 'NO' 'YES' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES' 'YES' 'YES' 'YES'
 'YES' 'YES' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO' 'YES' 'YES' 'NO' 'YES' 'NO'
 'NO' 'NO' 'NO' 'NO' 'NO' 'NO' 'YES' 'NO' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES'
 'YES' 'YES' 'NO' 'NO' 'NO' 'YES' 'NO' 'YES' 'NO' 'NO' 'NO' 'YES']


In [21]:
#Naive Bayes Classifier - Classification Report

print(classification_report(bd_target_test, nbpreds_test))

             precision    recall  f1-score   support

         NO       0.64      0.76      0.69        62
        YES       0.67      0.53      0.60        58

avg / total       0.65      0.65      0.65       120



In [22]:
#Naive Bayes Classifier - Confusion Matrix - Why is this zero???

nbcm = confusion_matrix(bd_target_test, nbpreds_test, labels=['Yes', 'No'])
print nbcm

[[0 0]
 [0 0]]


In [23]:
#Naive Bayes Classifier - Confusion Matrix Plot

pl.matshow(treecm)
pl.title('Tree Classifier Confusion Matrix')
pl.colorbar()
pl.ylabel('Actual')
pl.xlabel('Predicted')
pl.show()