In [2]:
import numpy as np
import kMeans
reload(kMeans)
import helper
reload(helper)
import kNN
reload(kNN)
#%reset - f

<module 'kNN' from 'kNN.pyc'>

In [3]:
imageData = np.genfromtxt('segmentation_data.txt',delimiter=',',dtype=float)

In [4]:
imageData

array([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
           0.50813884,    1.9108642 ],
       [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
           0.46332908,    1.9414649 ],
       [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
           0.48014903,    1.9879022 ],
       ..., 
       [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
           0.5409177 ,   -1.9963073 ],
       [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
           0.50308645,   -1.9434487 ],
       [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
           0.4799313 ,   -2.0293121 ]])

In [5]:
imageData

array([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
           0.50813884,    1.9108642 ],
       [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
           0.46332908,    1.9414649 ],
       [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
           0.48014903,    1.9879022 ],
       ..., 
       [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
           0.5409177 ,   -1.9963073 ],
       [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
           0.50308645,   -1.9434487 ],
       [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
           0.4799313 ,   -2.0293121 ]])

In [6]:
np.mat(imageData)

matrix([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
            0.50813884,    1.9108642 ],
        [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
            0.46332908,    1.9414649 ],
        [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
            0.48014903,    1.9879022 ],
        ..., 
        [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
            0.5409177 ,   -1.9963073 ],
        [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
            0.50308645,   -1.9434487 ],
        [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
            0.4799313 ,   -2.0293121 ]])

In [9]:
segClasses = np.genfromtxt('segmentation_classes.txt',delimiter='\t',dtype=None)
print segClasses
print segClasses.shape

[('GRASS', 0) ('GRASS', 0) ('GRASS', 0) ..., ('CEMENT', 3) ('CEMENT', 3)
 ('CEMENT', 3)]
(2100L,)


In [10]:
segClasses[208][1]

2

In [11]:
segNames = np.genfromtxt('segmentation_names.txt',delimiter='\t',dtype=(None))

In [12]:
print segNames
print segNames.shape
print len(segNames)

['REGION-CENTROID-COL' 'REGION-CENTROID-ROW' 'REGION-PIXEL-COUNT'
 'SHORT-LINE-DENSITY-5' 'SHORT-LINE-DENSITY-2' 'VEDGE-MEAN' 'VEDGE-SD'
 'HEDGE-MEAN' 'HEDGE-SD' 'INTENSITY-MEAN' 'RAWRED-MEAN' 'RAWBLUE-MEAN'
 'RAWGREEN-MEAN' 'EXRED-MEAN' 'EXBLUE-MEAN' 'EXGREEN-MEAN' 'VALUE-MEAN'
 'SATURATION-MEAN' 'HUE-MEAN']
(19L,)
19


In [13]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
imageData_norm = min_max_scaler.fit_transform(imageData)

In [14]:
reload(kMeans)
cents, clusts = kMeans.kMeans(imageData, 7, kMeans.distEclud)

In [15]:
cents

array([[  1.28017595e+02,   4.72258065e+01,   9.00000000e+00,
          1.14043661e-02,   6.51678065e-04,   1.04463997e+00,
          6.75502689e-01,   1.20576740e+00,   8.22678352e-01,
          1.11688932e+02,   1.00868361e+02,   1.28428155e+02,
          1.05770284e+02,  -3.24617138e+01,   5.02176605e+01,
         -1.77559465e+01,   1.28428155e+02,   2.22954812e-01,
         -2.27548943e+00],
       [  1.89166667e+02,   8.78333333e+01,   9.00000000e+00,
          0.00000000e+00,   1.85185183e-02,   2.30370365e+01,
          5.55769130e+02,   1.34351847e+01,   1.53996895e+02,
          3.84259262e+01,   3.28703703e+01,   4.72592595e+01,
          3.51481485e+01,  -1.66666668e+01,   2.64999998e+01,
         -9.83333335e+00,   4.72592595e+01,   3.74439798e-01,
         -2.24136388e+00],
       [  1.24315548e+02,   1.38753299e+02,   9.00000000e+00,
          1.57455216e-02,   4.84477588e-03,   1.89172562e+00,
          2.71279830e+00,   2.46095490e+00,   5.23418522e+00,
          2.2393

In [16]:
for i in range(len(segNames)):
    print "%11s\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f" %(segNames[i], cents[0][i],cents[1][i],cents[2][i],cents[3][i],cents[4][i],cents[5][i],cents[6][i])

REGION-CENTROID-COL	128.0176	189.1667	124.3155	134.5000	80.0000	226.0000	54.8333
REGION-CENTROID-ROW	47.2258	87.8333	138.7533	98.0000	87.0000	69.0000	80.8333
REGION-PIXEL-COUNT	9.0000	9.0000	9.0000	9.0000	9.0000	9.0000	9.0000
SHORT-LINE-DENSITY-5	0.0114	0.0000	0.0157	0.0000	0.0000	0.0000	0.0000
SHORT-LINE-DENSITY-2	0.0007	0.0185	0.0048	0.1111	0.1111	0.1111	0.0556
 VEDGE-MEAN	1.0446	23.0370	1.8917	14.8333	24.3889	19.1111	17.6389
   VEDGE-SD	0.6755	555.7691	2.7128	102.5074	572.9964	991.7184	320.7216
 HEDGE-MEAN	1.2058	13.4352	2.4610	32.3333	44.7222	20.4444	23.8611
   HEDGE-SD	0.8227	153.9969	5.2342	769.8962	1386.3292	1039.5408	384.2513
INTENSITY-MEAN	111.6889	38.4259	22.3937	42.8333	67.4444	23.8148	45.7531
RAWRED-MEAN	100.8684	32.8704	19.4615	35.8333	58.7778	19.2222	38.2593
RAWBLUE-MEAN	128.4282	47.2593	27.6573	52.6667	79.0000	29.3333	55.6296
RAWGREEN-MEAN	105.7703	35.1481	20.0622	40.0000	64.5556	22.8889	43.3704
 EXRED-MEAN	-32.4617	-16.6667	-8.7964	-21.0000	-26.0000	-13.7778	-22.4815
EX

In [17]:
clusts.shape

(2100L, 2L)

In [18]:
clusts

array([[  2.00000000e+00,   4.68730670e+03],
       [  2.00000000e+00,   5.59235516e+03],
       [  2.00000000e+00,   2.29853545e+04],
       ..., 
       [  2.00000000e+00,   1.83790231e+03],
       [  2.00000000e+00,   2.15398476e+03],
       [  2.00000000e+00,   1.39082138e+03]])

In [19]:
from sklearn.metrics import completeness_score, homogeneity_score

target = helper.createLabelsVector('segmentation_classes.txt', ["0", "1", "2", "3", "4", "5", "6"])
print len(target)

newC = np.ravel(clusts.T[0])
print "newC is: ", newC
newC=newC.astype(int)
print "size of newC is:", newC.shape

print "Completeness score:", completeness_score(target, newC)
print "Homogeneity score: ", homogeneity_score(target, newC)


2100
newC is:  [ 2.  2.  2. ...,  2.  2.  2.]
size of newC is: (2100L,)
Completeness score: 0.801544009141
Homogeneity score:  0.204809263981


In [20]:
from sklearn import decomposition

pca = decomposition.PCA(n_components=5)
imageDataNormTrans = pca.fit(imageData_norm).transform(imageData_norm)

In [21]:
np.set_printoptions(precision=2, suppress=True)
print imageDataNormTrans

[[-0.69  0.53 -0.25 -0.2  -0.08]
 [-0.67  0.51 -0.34 -0.17 -0.04]
 [-0.71  0.77  0.16 -0.01 -0.17]
 ..., 
 [-0.51 -0.13  0.08  0.1  -0.03]
 [-0.48 -0.09  0.16  0.11  0.  ]
 [-0.44 -0.11  0.05  0.15  0.02]]


In [22]:
print(pca.explained_variance_ratio_)

[ 0.61  0.13  0.1   0.05  0.04]


In [24]:
cents_pca, clusters_pca = kMeans.kMeans(imageDataNormTrans, 7, helper.distCosine)

In [25]:
print cents_pca

[[-0.44 -0.1   0.32 -0.06  0.06]
 [-0.43 -0.32 -0.15 -0.05  0.  ]
 [ 0.19  0.07  0.29  0.22 -0.  ]
 [-0.62  0.61 -0.18 -0.07 -0.03]
 [ 1.18  0.11  0.18 -0.14  0.01]
 [ 0.27 -0.06 -0.19  0.34 -0.09]
 [ 1.07 -0.07 -0.23 -0.09  0.02]]


In [26]:
newCpca = np.ravel(clusters_pca.T[0])

In [27]:
print newCpca

[ 3.  3.  3. ...,  0.  0.  0.]


In [28]:
print "Completeness: ", completeness_score(target, newCpca)
print "Homogeneity: ", homogeneity_score(target, newCpca)

Completeness:  0.586979407467
Homogeneity:  0.56769510472


In [31]:
reload(helper)

<module 'helper' from 'helper.py'>