In [20]:
# n=dataMat.shape[1]
# centroids=mat(zeros((n,k)))
# for j in range(n):
#     minJ=min(dataMat[:,j])
#     rangeJ=float(max(dataMat[:,j]) - minJ)
#     centroids[:,j]=minJ + rangeJ * random.rand(3)
# centroids

In [4]:
import kMeans
reload(kMeans)
from numpy import *

In [5]:
def loadDataSet(fileName):
    dataMat = []
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split('\t')
        fltLine = map(float,curLine)
        dataMat.append(fltLine)
    return dataMat

In [6]:
dataMat=mat(loadDataSet('testSet.txt'))

In [21]:
#dataMat

In [8]:
min(dataMat[:,0])

matrix([[-5.379713]])

In [9]:
min(dataMat[:,1])

matrix([[-4.232586]])

In [10]:
max(dataMat[:,1])

matrix([[ 5.1904]])

In [11]:
max(dataMat[:,0])

matrix([[ 4.838138]])

In [12]:
d=mat([[12, 2, 73, 15],
      [6, 89, 81, 29],
      [19, 78, 77, 92]])

min(d[:,0])  #Min in column 0 ==> 6
min(d[:,1])  #Min in column 1  ==> 2
min(d[:,2])  #Min in column 2 ==> 73
min(d[:,3])  #Min in column 3 ==> 15
max(d[:,0])  #Max in column 0 ==> 19
max(d[:,1])  #Max in column 1 ==> 89
max(d[:,2])  #Max in column 2 ==> 81
max(d[:,3])  #Max in column 3 ==> 92
d[0,:]       #Whole first row ==> [12, 2, 73, 15]

matrix([[12,  2, 73, 15]])

In [41]:
dataMat

matrix([[ 1.658985,  4.285136],
        [-3.453687,  3.424321],
        [ 4.838138, -1.151539],
        [-5.379713, -3.362104],
        [ 0.972564,  2.924086],
        [-3.567919,  1.531611],
        [ 0.450614, -3.302219],
        [-3.487105, -1.724432],
        [ 2.668759,  1.594842],
        [-3.156485,  3.191137],
        [ 3.165506, -3.999838],
        [-2.786837, -3.099354],
        [ 4.208187,  2.984927],
        [-2.123337,  2.943366],
        [ 0.704199, -0.479481],
        [-0.39237 , -3.963704],
        [ 2.831667,  1.574018],
        [-0.790153,  3.343144],
        [ 2.943496, -3.357075],
        [-3.195883, -2.283926],
        [ 2.336445,  2.875106],
        [-1.786345,  2.554248],
        [ 2.190101, -1.90602 ],
        [-3.403367, -2.778288],
        [ 1.778124,  3.880832],
        [-1.688346,  2.230267],
        [ 2.592976, -2.054368],
        [-4.007257, -3.207066],
        [ 2.257734,  3.387564],
        [-2.679011,  0.785119],
        [ 0.939512, -4.023563],
        

In [43]:
dataMat.shape

(80, 2)

In [53]:
import kMeans
reload(kMeans)

<module 'kMeans' from 'kMeans.py'>

In [54]:
cents, clust, ptsInCluster = kMeans.kMeans(dataMat, 4)

Points in cluster:  [[ 1.658985  4.285136]
 [-3.453687  3.424321]
 [ 0.972564  2.924086]
 [ 2.668759  1.594842]
 [-3.156485  3.191137]
 [ 4.208187  2.984927]
 [-2.123337  2.943366]
 [ 2.831667  1.574018]
 [-0.790153  3.343144]
 [ 2.336445  2.875106]
 [-1.786345  2.554248]
 [ 1.778124  3.880832]
 [-1.688346  2.230267]
 [ 2.257734  3.387564]
 [ 2.046259  2.735279]
 [-3.18947   1.780269]
 [ 1.889034  5.1904  ]
 [-0.798747  2.185588]
 [ 2.096701  3.886007]
 [-2.709034  2.923887]
 [ 2.329546  3.179764]
 [-3.284816  3.273099]
 [ 3.542056  2.778832]
 [-1.736822  4.241041]
 [ 3.792121  5.135768]
 [-4.786473  3.358547]
 [ 2.493525  1.96371 ]
 [-2.513661  2.642162]
 [ 2.89422   2.489128]
 [-2.562539  2.884438]
 [ 3.332948  3.983102]
 [-1.616805  3.573188]
 [ 2.321395  3.154987]
 [-1.685703  2.939697]
 [ 4.196223  1.126677]
 [-2.133863  3.093686]
 [ 2.884105  3.043438]
 [-2.967647  2.848696]]
Shape of ptsInClust:  (38, 2)
Points in cluster:  [[ 1.658985  4.285136]
 [-3.453687  3.424321]
 [ 0.9725

In [55]:
ptsInCluster

matrix([[ 1.658985,  4.285136],
        [ 0.972564,  2.924086],
        [ 2.668759,  1.594842],
        [ 4.208187,  2.984927],
        [ 2.831667,  1.574018],
        [ 2.336445,  2.875106],
        [ 1.778124,  3.880832],
        [ 2.257734,  3.387564],
        [ 2.046259,  2.735279],
        [ 1.889034,  5.1904  ],
        [ 2.096701,  3.886007],
        [ 2.329546,  3.179764],
        [ 3.542056,  2.778832],
        [ 3.792121,  5.135768],
        [ 2.493525,  1.96371 ],
        [ 2.89422 ,  2.489128],
        [ 3.332948,  3.983102],
        [ 2.321395,  3.154987],
        [ 4.196223,  1.126677],
        [ 2.884105,  3.043438]])

In [22]:
cents

array([[ 2.80293085, -2.7315146 ],
       [ 2.6265299 ,  3.10868015],
       [-2.46154315,  2.78737555],
       [-3.38237045, -2.9473363 ]])

In [23]:
clust.shape

(80, 2)

In [42]:
clust

array([[  3.00000000e+00,   2.32019150e+00],
       [  2.00000000e+00,   1.39004893e+00],
       [  1.00000000e+00,   6.63839104e+00],
       [  0.00000000e+00,   4.16140951e+00],
       [  3.00000000e+00,   2.76967820e+00],
       [  2.00000000e+00,   2.80101213e+00],
       [  1.00000000e+00,   5.85909807e+00],
       [  0.00000000e+00,   1.50646425e+00],
       [  3.00000000e+00,   2.29348924e+00],
       [  2.00000000e+00,   6.45967483e-01],
       [  1.00000000e+00,   1.74010499e+00],
       [  0.00000000e+00,   3.77769471e-01],
       [  3.00000000e+00,   2.51695402e+00],
       [  2.00000000e+00,   1.38716420e-01],
       [  1.00000000e+00,   9.47633071e+00],
       [  0.00000000e+00,   9.97310599e+00],
       [  3.00000000e+00,   2.39726914e+00],
       [  2.00000000e+00,   3.10242360e+00],
       [  1.00000000e+00,   4.11084375e-01],
       [  0.00000000e+00,   4.74890795e-01],
       [  3.00000000e+00,   1.38706133e-01],
       [  2.00000000e+00,   5.10240996e-01],
       [  

In [25]:
ptsInCluster.shape

(20, 2)

In [44]:
dataMat.shape

(80, 2)

In [ ]:
zz=dataMat[nonzero(clust[:,0]==0)[0]]
zz

In [ ]:
clust[:,0]

In [ ]:
clust[:,0]==0

In [ ]:
nonzero(clust[:,0]==0)