In [2]:
import numpy as np
import kNN
reload(kNN)
import kMeans
reload(kMeans)
import helper
reload(helper)
#%reset -f

<module 'helper' from 'helper.pyc'>

In [3]:
TD=np.genfromtxt('term-doc-mat.csv',delimiter=',', usecols=(range(1,16)),dtype=int)

In [4]:
terms=np.genfromtxt('term-doc-mat.csv',delimiter=',',usecols=(0),dtype=str)

In [5]:
print terms

['database' 'index' 'likelihood' 'linear' 'matrix' 'query' 'regression'
 'retrieval' 'sql' 'vector']


In [6]:
print TD

[[24 32 12  6 43  2  0  3  1  6  4  0  0  0  0]
 [ 9  5  5  2 20  0  1  0  0  0 27 14  3  2 11]
 [ 0  3  0  0  3  7 12  4 27  4  0  1  0  0  0]
 [ 3  0  0  0  0 16  0  2 25 23  7 12 21  3  2]
 [ 1  0  0  0  0 33  2  0  7 12 14  5 12  4  0]
 [12  2  0  0 27  0  0  0  0 22  9  4  0  5  3]
 [ 0  0  0  0  0 18 32 22 34 17  0  0  0  0  0]
 [ 1  0  0  0  2  0  0  0  3  9 27  7  5  4  4]
 [21 10 16  7 31  0  0  0  0  0  0  0  0  1  0]
 [ 2  0  0  2  0 27  4  2 11  8 33 16 14  7  3]]


In [7]:
DT=TD.T

In [16]:
DT

array([[24,  9,  0,  3,  1, 12,  0,  1, 21,  2],
       [32,  5,  3,  0,  0,  2,  0,  0, 10,  0],
       [12,  5,  0,  0,  0,  0,  0,  0, 16,  0],
       [ 6,  2,  0,  0,  0,  0,  0,  0,  7,  2],
       [43, 20,  3,  0,  0, 27,  0,  2, 31,  0],
       [ 2,  0,  7, 16, 33,  0, 18,  0,  0, 27],
       [ 0,  1, 12,  0,  2,  0, 32,  0,  0,  4],
       [ 3,  0,  4,  2,  0,  0, 22,  0,  0,  2],
       [ 1,  0, 27, 25,  7,  0, 34,  3,  0, 11],
       [ 6,  0,  4, 23, 12, 22, 17,  9,  0,  8],
       [ 4, 27,  0,  7, 14,  9,  0, 27,  0, 33],
       [ 0, 14,  1, 12,  5,  4,  0,  7,  0, 16],
       [ 0,  3,  0, 21, 12,  0,  0,  5,  0, 14],
       [ 0,  2,  0,  3,  4,  5,  0,  4,  1,  7],
       [ 0, 11,  0,  2,  0,  3,  0,  4,  0,  3]])

In [9]:
w=kNN.generateWeightedMatrix(TD)

orig[t,:] is:  [24 32 12  6 43  2  0  3  1  6  4  0  0  0  0]
nk is:  10
orig[t,:] is:  [ 9  5  5  2 20  0  1  0  0  0 27 14  3  2 11]
nk is:  11
orig[t,:] is:  [ 0  3  0  0  3  7 12  4 27  4  0  1  0  0  0]
nk is:  8
orig[t,:] is:  [ 3  0  0  0  0 16  0  2 25 23  7 12 21  3  2]
nk is:  10
orig[t,:] is:  [ 1  0  0  0  0 33  2  0  7 12 14  5 12  4  0]
nk is:  9
orig[t,:] is:  [12  2  0  0 27  0  0  0  0 22  9  4  0  5  3]
nk is:  8
orig[t,:] is:  [ 0  0  0  0  0 18 32 22 34 17  0  0  0  0  0]
nk is:  5
orig[t,:] is:  [ 1  0  0  0  2  0  0  0  3  9 27  7  5  4  4]
nk is:  9
orig[t,:] is:  [21 10 16  7 31  0  0  0  0  0  0  0  0  1  0]
nk is:  6
orig[t,:] is:  [ 2  0  0  2  0 27  4  2 11  8 33 16 14  7  3]
nk is:  12


In [10]:
np.set_printoptions(precision=2,suppress=True)
w=w.T
w

array([[ 14.04,   4.03,   0.  ,   1.75,   0.74,  10.88,   0.  ,   0.74,  27.76,   0.64],
       [ 18.72,   2.24,   2.72,   0.  ,   0.  ,   1.81,   0.  ,   0.  ,  13.22,   0.  ],
       [  7.02,   2.24,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  21.15,   0.  ],
       [  3.51,   0.89,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   9.25,   0.64],
       [ 25.15,   8.95,   2.72,   0.  ,   0.  ,  24.49,   0.  ,   1.47,  40.98,   0.  ],
       [  1.17,   0.  ,   6.35,   9.36,  24.32,   0.  ,  28.53,   0.  ,   0.  ,   8.69],
       [  0.  ,   0.45,  10.88,   0.  ,   1.47,   0.  ,  50.72,   0.  ,   0.  ,   1.29],
       [  1.75,   0.  ,   3.63,   1.17,   0.  ,   0.  ,  34.87,   0.  ,   0.  ,   0.64],
       [  0.58,   0.  ,  24.49,  14.62,   5.16,   0.  ,  53.89,   2.21,   0.  ,   3.54],
       [  3.51,   0.  ,   3.63,  13.45,   8.84,  19.95,  26.94,   6.63,   0.  ,   2.58],
       [  2.34,  12.08,   0.  ,   4.09,  10.32,   8.16,   0.  ,  19.9 ,   0.  ,  10.62],
       [  0.  ,   6.2

In [11]:
cents, clusts, ptsCluster = kMeans.kMeans(w, 3, helper.distEclud)

centroids[j,:] is:  [  3.1    2.28   9.17  14.41  13.69  22.44  15.59   2.44   2.64   5.61]
datSet[i,:] is:  [ 14.04   4.03   0.     1.75   0.74  10.88   0.     0.74  27.76   0.64]
minDist is:  39.6235783871
centroids[j,:] is:  [  0.25   8.63  16.45  12.64  23.51  19.41  43.14   3.53  14.23   1.83]
datSet[i,:] is:  [ 14.04   4.03   0.     1.75   0.74  10.88   0.     0.74  27.76   0.64]
centroids[j,:] is:  [ 17.41  10.42   0.57  13.66  17.53  21.3   34.9   19.86  21.49   8.98]
datSet[i,:] is:  [ 14.04   4.03   0.     1.75   0.74  10.88   0.     0.74  27.76   0.64]
centroids[j,:] is:  [  3.1    2.28   9.17  14.41  13.69  22.44  15.59   2.44   2.64   5.61]
datSet[i,:] is:  [ 18.72   2.24   2.72   0.     0.     1.81   0.     0.    13.22   0.  ]
minDist is:  38.7095160104
centroids[j,:] is:  [  0.25   8.63  16.45  12.64  23.51  19.41  43.14   3.53  14.23   1.83]
datSet[i,:] is:  [ 18.72   2.24   2.72   0.     0.     1.81   0.     0.    13.22   0.  ]
centroids[j,:] is:  [ 17.41  10.42   0.57

In [12]:
cents

array([[  3.95,   3.86,   0.45,   3.29,   3.22,   2.61,   0.  ,   4.33,   5.62,   3.02],
       [  1.4 ,   0.09,   9.79,   7.72,   7.96,   3.99,  38.99,   1.77,   0.  ,   3.35],
       [ 19.6 ,   6.49,   1.36,   0.88,   0.37,  17.68,   0.  ,   1.11,  34.37,   0.32]])

In [13]:
for i in range(10):
    print "%10s\t%.4f\t\t%.4f\t\t%.4f" %(terms[i], cents[0][i],cents[1][i],cents[2][i])

  database	3.9485		1.4039		19.5962
     index	3.8593		0.0895		6.4882
likelihood	0.4534		9.7944		1.3603
    linear	3.2904		7.7215		0.8774
    matrix	3.2242		7.9592		0.3685
     query	2.6073		3.9903		17.6844
regression	0.0000		38.9901		0.0000
 retrieval	4.3297		1.7687		1.1054
       sql	5.6182		0.0000		34.3701
    vector	3.0181		3.3481		0.3219


In [14]:
print clusts

[[   2.    129.88]
 [   0.    333.42]
 [   0.    309.41]
 [   0.     74.8 ]
 [   2.    129.88]
 [   1.    439.33]
 [   1.    265.82]
 [   1.    187.78]
 [   1.    510.14]
 [   1.    500.23]
 [   0.    484.  ]
 [   0.     73.54]
 [   0.    175.59]
 [   0.     51.68]
 [   0.     69.52]]


In [15]:
print cents

[[  3.95   3.86   0.45   3.29   3.22   2.61   0.     4.33   5.62   3.02]
 [  1.4    0.09   9.79   7.72   7.96   3.99  38.99   1.77   0.     3.35]
 [ 19.6    6.49   1.36   0.88   0.37  17.68   0.     1.11  34.37   0.32]]


In [19]:
cents2, clusts2, ptsCluster2 = kMeans.kMeans(DT, 3, helper.distCosine)

centroids[j,:] is:  [  8.     7.01  17.36   8.97  28.93  13.52   4.32  13.33   6.67  20.18]
datSet[i,:] is:  [24  9  0  3  1 12  0  1 21  2]
vecA is:  [  8.     7.01  17.36   8.97  28.93  13.52   4.32  13.33   6.67  20.18]
vecB is:  [24  9  0  3  1 12  0  1 21  2]
norm_A is:  46.5074910321
norm_B is:  35.4541958025
cosine is:  508.426482197
distance is:  -507.426482197
minDist is:  -507.426482197
centroids[j,:] is:  [  7.91   9.69   3.52  18.38  30.46  20.39   2.25  21.55  21.96   1.89]
datSet[i,:] is:  [24  9  0  3  1 12  0  1 21  2]
vecA is:  [  7.91   9.69   3.52  18.38  30.46  20.39   2.25  21.55  21.96   1.89]
vecB is:  [24  9  0  3  1 12  0  1 21  2]
norm_A is:  52.9673684159
norm_B is:  35.4541958025
cosine is:  732.242953331
distance is:  -731.242953331
minDist is:  -731.242953331
centroids[j,:] is:  [ 15.86  10.84  21.5   11.42  29.39  10.15  32.44   8.37   7.21  15.2 ]
datSet[i,:] is:  [24  9  0  3  1 12  0  1 21  2]
vecA is:  [ 15.86  10.84  21.5   11.42  29.39  10.15  32.44

In [20]:
for i in range(10):
    print "%10s\t%.4f\t\t%.4f\t\t%.4f" %(terms[i], cents2[0][i],cents2[1][i],cents2[2][i])

  database	0.8000		23.4000		2.4000
     index	11.4000		8.2000		0.2000
likelihood	0.2000		1.2000		10.8000
    linear	9.0000		0.6000		13.2000
    matrix	7.0000		0.2000		10.8000
     query	4.2000		8.2000		4.4000
regression	0.0000		0.0000		24.6000
 retrieval	9.4000		0.6000		2.4000
       sql	0.2000		17.0000		0.0000
    vector	14.6000		0.8000		10.4000


In [21]:
clusts2

array([[        1.  ,   1545110.63],
       [        1.  ,   1143308.94],
       [        1.  ,    153089.98],
       [        1.  ,      7177.91],
       [        1.  ,  15004672.04],
       [        2.  ,   3999466.45],
       [        2.  ,    989866.61],
       [        2.  ,    182316.72],
       [        2.  ,   6412196.44],
       [        2.  ,   1756854.71],
       [        0.  ,   7722262.9 ],
       [        0.  ,    452626.28],
       [        0.  ,    437258.99],
       [        0.  ,     11585.35],
       [        0.  ,     15206.71]])