In [22]:
import numpy as np
import kMeans
reload(kMeans)
import helper
reload(helper)
#import kNN
#reload(kNN)
#%reset - f

<module 'helper' from 'helper.pyc'>

In [23]:
imageData = np.genfromtxt('segmentation_data.txt',delimiter=',',dtype=float)

In [24]:
imageData

array([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
           0.50813884,    1.9108642 ],
       [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
           0.46332908,    1.9414649 ],
       [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
           0.48014903,    1.9879022 ],
       ..., 
       [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
           0.5409177 ,   -1.9963073 ],
       [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
           0.50308645,   -1.9434487 ],
       [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
           0.4799313 ,   -2.0293121 ]])

In [25]:
imageData

array([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
           0.50813884,    1.9108642 ],
       [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
           0.46332908,    1.9414649 ],
       [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
           0.48014903,    1.9879022 ],
       ..., 
       [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
           0.5409177 ,   -1.9963073 ],
       [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
           0.50308645,   -1.9434487 ],
       [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
           0.4799313 ,   -2.0293121 ]])

In [26]:
np.mat(imageData)

matrix([[ 110.        ,  189.        ,    9.        , ...,   18.666668  ,
            0.50813884,    1.9108642 ],
        [  86.        ,  187.        ,    9.        , ...,   19.222221  ,
            0.46332908,    1.9414649 ],
        [ 225.        ,  244.        ,    9.        , ...,   17.11111   ,
            0.48014903,    1.9879022 ],
        ..., 
        [ 128.        ,  161.        ,    9.        , ...,   10.888889  ,
            0.5409177 ,   -1.9963073 ],
        [ 150.        ,  158.        ,    9.        , ...,   12.222222  ,
            0.50308645,   -1.9434487 ],
        [ 124.        ,  162.        ,    9.        , ...,   14.555555  ,
            0.4799313 ,   -2.0293121 ]])

In [27]:
segClasses = np.genfromtxt('segmentation_classes.txt',delimiter='\t',dtype=None)
print segClasses
print segClasses.shape

[('GRASS', 0) ('GRASS', 0) ('GRASS', 0) ..., ('CEMENT', 3) ('CEMENT', 3)
 ('CEMENT', 3)]
(2100L,)


In [28]:
segClasses[208][1]

2

In [29]:
segNames = np.genfromtxt('segmentation_names.txt',delimiter='\t',dtype=(None))

In [30]:
print segNames
print segNames.shape
print len(segNames)

['REGION-CENTROID-COL' 'REGION-CENTROID-ROW' 'REGION-PIXEL-COUNT'
 'SHORT-LINE-DENSITY-5' 'SHORT-LINE-DENSITY-2' 'VEDGE-MEAN' 'VEDGE-SD'
 'HEDGE-MEAN' 'HEDGE-SD' 'INTENSITY-MEAN' 'RAWRED-MEAN' 'RAWBLUE-MEAN'
 'RAWGREEN-MEAN' 'EXRED-MEAN' 'EXBLUE-MEAN' 'EXGREEN-MEAN' 'VALUE-MEAN'
 'SATURATION-MEAN' 'HUE-MEAN']
(19L,)
19


In [31]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
imageData_norm = min_max_scaler.fit_transform(imageData)

In [32]:
reload(kMeans)
cents, clusts = kMeans.kMeans(imageData, 7, kMeans.distEclud)

In [33]:
cents

array([[  8.00000000e+01,   8.70000000e+01,   9.00000000e+00,
          0.00000000e+00,   1.11111110e-01,   2.43888910e+01,
          5.72996400e+02,   4.47222250e+01,   1.38632920e+03,
          6.74444400e+01,   5.87777800e+01,   7.90000000e+01,
          6.45555600e+01,  -2.60000000e+01,   3.46666680e+01,
         -8.66666700e+00,   7.90000000e+01,   3.06281270e-01,
         -2.42212720e+00],
       [  2.39142847e+02,   1.33025656e+02,   9.00000000e+00,
          2.23971183e-01,   1.71011456e-01,   1.93114930e+01,
          6.93909471e+02,   2.70353623e+01,   7.62084564e+02,
          1.03483644e+02,   6.40355016e+01,   6.05925197e+01,
          2.32535883e+01,  -7.72698852e+00,   7.82005532e+01,
          2.17270799e+01,   1.16602215e+02,   6.78896093e-01,
         -1.34674062e+00],
       [  1.00333333e+02,   9.16666667e+01,   9.00000000e+00,
          0.00000000e+00,   7.40740733e-02,   2.02407407e+01,
          1.98151900e+02,   2.64629623e+01,   4.92366690e+02,
          4.4691

In [34]:
for i in range(len(segNames)):
    print "%11s\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f\t%.4f" %(segNames[i], cents[0][i],cents[1][i],cents[2][i],cents[3][i],cents[4][i],cents[5][i],cents[6][i])

REGION-CENTROID-COL	80.0000	239.1428	100.3333	124.8782	226.0000	157.7500	67.5000
REGION-CENTROID-ROW	87.0000	133.0257	91.6667	123.7540	69.0000	86.0000	84.5000
REGION-PIXEL-COUNT	9.0000	9.0000	9.0000	9.0000	9.0000	9.0000	9.0000
SHORT-LINE-DENSITY-5	0.0000	0.2240	0.0000	0.0150	0.0000	0.0000	0.0000
SHORT-LINE-DENSITY-2	0.1111	0.1710	0.0741	0.0042	0.1111	0.0139	0.1111
 VEDGE-MEAN	24.3889	19.3115	20.2407	1.7560	19.1111	21.4306	16.8889
   VEDGE-SD	572.9964	693.9095	198.1519	2.4705	991.7184	516.5778	272.3371
 HEDGE-MEAN	44.7222	27.0354	26.4630	2.2582	20.4444	15.5556	38.3889
   HEDGE-SD	1386.3292	762.0846	492.3667	4.6069	1039.5408	192.3426	775.8592
INTENSITY-MEAN	67.4444	103.4836	44.6914	36.9936	23.8148	40.0833	61.2407
RAWRED-MEAN	58.7778	64.0355	37.2593	32.7703	19.2222	33.9444	53.3333
RAWBLUE-MEAN	79.0000	60.5925	55.1481	44.1343	29.3333	49.2083	72.0556
RAWGREEN-MEAN	64.5556	23.2536	41.6667	34.0761	22.8889	37.0972	58.3333
 EXRED-MEAN	-26.0000	-7.7270	-22.2963	-12.6699	-13.7778	-18.4167	-23.722

In [35]:
clusts.shape

(2100L, 2L)

In [36]:
clusts

array([[  3.00000000e+00,   9.49479391e+03],
       [  3.00000000e+00,   1.02380718e+04],
       [  3.00000000e+00,   2.94077109e+04],
       ..., 
       [  3.00000000e+00,   6.34972925e+03],
       [  3.00000000e+00,   6.35817509e+03],
       [  3.00000000e+00,   5.43774060e+03]])

In [37]:
from sklearn.metrics import completeness_score, homogeneity_score

target = helper.createLabelsVector('segmentation_classes.txt', ["0", "1", "2", "3", "4", "5", "6"])
print len(target)

newC = np.ravel(clusts.T[0])
print "newC is: ", newC
newC=newC.astype(int)
print "size of newC is:", newC.shape

print "Completeness score:", completeness_score(target, newC)
print "Homogeneity score: ", homogeneity_score(target, newC)


2100
newC is:  [ 3.  3.  3. ...,  3.  3.  3.]
size of newC is: (2100L,)
Completeness score: 0.230025400987
Homogeneity score:  0.00610040863731


In [38]:
from sklearn import decomposition

pca = decomposition.PCA(n_components=5)
imageDataNormTrans = pca.fit(imageData_norm).transform(imageData_norm)

In [39]:
np.set_printoptions(precision=2, suppress=True)
print imageDataNormTrans

[[-0.69  0.53 -0.25 -0.2  -0.08]
 [-0.67  0.51 -0.34 -0.17 -0.04]
 [-0.71  0.77  0.16 -0.01 -0.17]
 ..., 
 [-0.51 -0.13  0.08  0.1  -0.03]
 [-0.48 -0.09  0.16  0.11  0.  ]
 [-0.44 -0.11  0.05  0.15  0.02]]


In [40]:
print(pca.explained_variance_ratio_)

[ 0.61  0.13  0.1   0.05  0.04]


In [41]:
cents_pca, clusters_pca = kMeans.kMeans(imageDataNormTrans, 7, helper.distCosine)

In [42]:
print cents_pca

[[ 1.33  0.08 -0.01 -0.16 -0.02]
 [ 0.25 -0.04 -0.17  0.35 -0.09]
 [ 0.19  0.07  0.3   0.2   0.01]
 [-0.43 -0.32 -0.15 -0.05  0.  ]
 [-0.44 -0.1   0.32 -0.06  0.06]
 [ 0.54 -0.2  -0.18  0.05  0.07]
 [-0.62  0.61 -0.18 -0.07 -0.03]]


In [43]:
newCpca = np.ravel(clusters_pca.T[0])

In [44]:
print newCpca

[ 6.  6.  6. ...,  4.  4.  4.]


In [45]:
print "Completeness: ", completeness_score(target, newCpca)
print "Homogeneity: ", homogeneity_score(target, newCpca)

Completeness:  0.635517311688
Homogeneity:  0.607510955545


In [46]:
reload(helper)

<module 'helper' from 'helper.pyc'>